### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by serussell** [andmarti1424/sc-im#160]
Hi!

Is there a wiki, or any sort of documentation other than :help? I've hit the limits of what I can figure out with reasonable trial-and-error, and the examples in the repo are limited to the trivial use cases.  Best would be a repository with some more advanced examples.  For example, I have a feeling that @sum(R, X) can be used to perform a sumif(), but I inevitably get stuck on a single missing bit of information.  Again, in my sumif() example, sum the value in A if the value in B matches G1:

   @sum(A1:A100, @eqs("G1", @svar("B", @frow( ??? ))))

How do I get the cell or row of what's being evaluated during the sum?  But this is just an example; I've hit three or four of these "almost" cases, and what I really need is a FAQ, or a good library of examples.  Does any such thing exist?

Thanks,

--- SER

**Comment by andmarti1424** [comment]
Hello. No, that is the only doc right now.
Some are working on improving it.

you cant use "," inside a @sum formula..
It might be added in future though.
Instead of @sum(A1:A100, G1).. you should use @sum(A1:A100) + G1..

did you check the @if example using @eqs??

**Comment by serussell** [comment]
Hi,
Thanks for the response.  The documentation for @sum says:

    @sum({range})                                                                                                                                              
    @sum({range},{expr})                                                                                                                                       
        Sum up the values.                  
                                                                                                                   
What does the second form mean?

I don't see documentation in :help for @if, and I don't see an example of its use in @eqs; where would I find this example?  

I'm using 0.5.0 -- is there more documentation in tip?

Thanks!

**Comment by andmarti1424** [comment]
well, second line seems a mistake. have to fix it.
yep.may be the example of @if with @eqs is not in v0.5, but in freeze branch doc file.

@if({expr}, {expr}, {expr})                                                                                                     
Conditional:   If the  first  expression  is  true  then  the  value  of
the  second  is  returned,  otherwise the  value  of  the  third.
example of use: @if(@eqs(A1,"a"),B1,0)

**Comment by brucehohl** [comment]
Based on my testing the following will work with @sum():
@sum(D1:D20,@eqs(C1,"s")) where s can be any string making this work like a sumif() (note 1)
@sum(D1:D20,D1>25) or @sum(D1:D20,E1>25) so 2nd parameter can reference different column.
It seems the second parameter must be numeric or return a numeric - 0 or 1 in the case of @eqs().  Also, make sure the second parameter cell reference is the same row number as the start of the sum range in the first parameter like in the above examples, otherwise, you will get unexpected results.  Someone will probably have to look at the code to see exactly how the 2nd parameter works.

Note 1: Instead of "s" I was not able to use a reference to a cell which contained "s".

**Comment by andmarti1424** [comment]
yep. you are right. second line, its not a mistake. The @sum, @prod, @avg, @count, @max, @min, and @stddev functions may take an optional second argument which is an expression that is to be evaluated for each cell in the specified range to determine which cells to include in the function. Only those cells for which the expression evaluates to true (non-zero will be used in calculating the value of the function.

**Comment by andmarti1424** [comment]
Added this to doc..

**Comment by serussell** [comment]
Beautiful, thanks.  I ended up with `@sum(E1:E1107,@eqs(B1,$G$1))` to create a sort of pivot table; the only awkward part was needing to anchor the second argument to `eqs`.  As @brucehohl points out, the ranging doesn't quite work unless either everything lines up, or the arguments are anchored.

In any case, this is forward progress and gives me a way to solve a problem -- thanks for the help!

**Comment by andmarti1424** [comment]
Does this works the same to you, in original sc ??

**Comment by serussell** [comment]
@andmarti1424, I've never used the original sc, so I couldn't say.
