### ISSUE TITLE
Support entering content wider that COLS

### ISSUE THREAD

**Issue by ber532k** [andmarti1424/sc-im#200]
If I try to input any string or number that takes more space than the input line is long, input just stops. If I input a long string by other means (e. g. creating some csv-file with vim), I am able to edit that string, but not add characters. Also the cursor doesn't display correctly on the second line.

**Comment by andmarti1424** [comment]
"If I try to input any string or number that takes more space than the input line is long, input just stops." -> this is on purpose.  right now, its just a window, not a pad. Do you really need to enter longer strings?
sc just overlaps to grid. in scim input window is just one line.

**Comment by ber532k** [comment]
I totally agree that this is anything but critical and I can do very well without long input. Just thought you might want to keep this in mind, as to maybe address it in some future version. Maybe splitting long strings into multiple lines and moving between them when the cursor leaves the available space might be an option.

**Comment by loopzen** [comment]
Hello! I miss this feature too. I agree with us. Spreadsheets shouldnt have long strings, but its possible to need work with spreadsheet created by people who use the spreadsheets like books. In this cases we need to access to this information. I love this software and i would like to use it more, but I have to work with longs string (xml output messages). By this motive Im using the awful Excel.

Anyway, congratulations for this beautiful software.

**Comment by mjk-gh** [comment]
I'm just getting started using sc-im, and this issue hit me immediately:
While I relatively rarely deal with spread-sheets with extra long lines, I often very deal with multi-line cell content, e.g.

Capacity | Ceramic<br>Noname | Film<br>WIMA | Film<br>Vishay | Aluminum | Tantalum
-------------|--------------|--------------|--------------|------------|----------
8.2 pF        |   100       |    50        |    73    |     90     |   34
10 pF     | 80  | 20 | 77 | - | 12
12 pF     | 10  | - | 35 | 204 | 18

It would probably be helpful to have a cell-individually configurable cell format property "automatic-linewrap: yes (=word) | word | char | no", with "word" trying to wrap at word boundaries, if possible.

To be able to distinguish between hard newlines and auto-linewrap-created soft newlines (which are not stored in the spreadsheet, but inserted dynamically), sc-im could additionally support highlighting special characters, configurable like this:

```
# Which characters to display instead of whitespace, soft-newline, hard-newline:
# (0xb7 is "middle dot" nad 0xb6 is "Pilcrow" in Latin9 aka ISO-8859-15)
SPECIAL_CHARS_HIGHLIGHT (0xb7, "+", 0xb6)
SPECIAL_CHARS_COLOR RED on NONE
```

Another nicety in this context would be colspan cells, but that's not quite a pressing issue, as you can just repeat the cell content -- ugly, but works.

Thanks for your consideration! Otherwise, sc-im seems so promising, that even Emacs-binding-users like me want to use it. :-)

**Comment by andmarti1424** [comment]
hello @mjk-gh. i have added support for rows to have more than 1 line of height, a couple of days ago.
and after that cell wrap.
you have to set no overlap and no truncate for that.
its in testing though.
currently working on having multiple frozen rows/columns.. but is soo much work. it will take long.

**Comment by mjk-gh** [comment]
Yippee, that sounds like good news!

Can you give me a little advice on how to test this feature?

I did the following:
1. ``git clone https://github.com/libxls/libxls.git``
2. compiled and installed libxls
3. ``git clone https://github.com/andmarti1424/sc-im.git``
4. compiled and installed sc-im
5. There are no ``~/.scimrc`` and no ``~/.config/sc-im/*``
6. Start sc-im
7. [ENTER] (to enter NORMAL mode)
8. ``:set truncate off`` [ENTER]
9. ``:set overlap off`` [ENTER]
10. ``>asdf lkj asdf lkj asdf lkj`` [ENTER]
After that, I see the full cell content in the status(?) line on the top, but the cell itself shows only a truncated string.
11. I then hit [ENTER] again, which adjusts the cell width to the width of its content (bug or feature?). No wrapping in sight.
12. Then I enter an extra long line of text into the next cell (B0), in the hopes that A0 and B0 would now both have wrap-around texts, but to no avail: Both cells show their text in 1 line (just A0 and B0 are not visible at the same time on the screen anymore, because they occupy too much space together).

I am using Debian 10.9 ("Buster", amd64) and GNU screen in a normal xterm (with Latin9 font, i.e. ISO-8859-15, and TERM=screen-bce) or without screen in an xterm with TERM=xterm-256color.


Btw.: After e.g. ":set overlap off", sc-im confirms with the message

  "Config value changed: overlap"

I think it would be better for it to print

  "Config value for 'overlap' changed to 'off'"

or similar, so that the user can be sure he didn't type something that sc-im would misinterpret (like "0" instead of "off" etc.).

**Comment by andmarti1424** [comment]
try increasing row height with `fj`

**Comment by mjk-gh** [comment]
Ahaaa.... oh. Well, fj increases the row height, indeed. But the symptoms seem to be the same ...

{ A few minutes later }

Oh! ``:set truncate off`` is *not* the same as ``:set notruncate on``!
Same for ``:set overlap off`` vs. ``:set nooverlap on``.

If I use the notruncate/nooverlap variables, multi-line rows seem to work, yay! :)
Might be a bit buggy, I have to test a little more.

Suggestion: Either:
- avoid negative variable names, as it will lead to double-negation in case of negative values (which needs an astonishingly high amount of brain processing power for many people) **or**
- let both negative and non-negative variables co-exist, so ``:set truncate off`` is the same as ``:set notruncate on``.

During testing the auto-wrap feature, two questions arose:

I have only ever worked with GUI spread-sheet calculators, and the ENTER key usually either advances one cell (horizontally or vertically) or starts editing the current cell content. In sc-im, however, this seems to execute "adapt cell width to content width", which is ... counter-intuitive. :-} Also, I cannot find that behavior documented in the help file. So:
1. Is it possible to find out the mapping for a key? ``:nmap "<CR>"`` leads to a syntax error.
2. How can I remap [ENTER] in sc-im? ``:nunmap "<CR>"`` seems to get accepted, but [ENTER] still adjusts the cell width. ``:nunmap <CR>`` leads to a syntax error.

**Comment by mjk-gh** [comment]
Tried ``:showmaps`` to find out which function or key sequence is bound to &lt;CR&gt; in NORMAL mode, but I just get an empty list ("Press 'q' and then ENTER to return"). The description in the help files reads:

```
  :showmaps       Show all key mappings.
```

**Comment by mjk-gh** [comment]
Also: Dear andmarti1424, even if I may seem like a greedy and demanding user, I am grateful that you are actively maintaining sc-im! <3

Now back to my demands. ;)

Do you happen to already have a "hard newline" feature implemented, like if the user hits "Shift-ENTER", an actual newline character gets inserted in the cell's text content?

As a current workaround, I insert the appropriate number of spaces, so that the auto-wrap happens at the desired position in the string. It's a workaround I can currently live with, so don't feel pressed about implementing it! I'm already happy with the existence of the auto-wrap feature!

**Comment by andmarti1424** [comment]
@mjk-gh, try this  mapping
`nmap "<cr>" "="`

Shift enter does not get captured in ncurses.
the newline(\n) will work in wrapped cells. but that is not done yet. would be done after this:

The mods to support multiple frozen rows / columns requires a lot of work.
But I also have my own job.. so it will take some time.

**Comment by andmarti1424** [comment]
@mjk-gh I have added auto wrap feature in the dev branch called "new". Please feel free to test it.
See doc file on how to use it.

**Comment by andmarti1424** [comment]
@ber532k @loopzen @mjk-gh, with my latest commit in the "new" branch, you can now use autowrap option to 
cover long strings. it will increase row height to fit the content.
You can also type \n when entering strings and it will increase row height as well.
Please check doc file and feel free to test it.
Thanks!
