### ISSUE TITLE
Automatically refresh the screen after suspend

### ISSUE THREAD

**Issue by jimu** [andmarti1424/sc-im#213]
I use <kbd>Ctrl+Z</kbd> to shell out, run commands, and then `fg` to return to scim.   However, now the screen is garbaged up and I have to press <kbd>Ctrl+L</kbd><kbd>ENTER</kbd> to refresh the screen.  

I'd like scim to do this automatically.

<b>Screen after using `fg` to return to scim</b>
![screen after using fg return to scim](https://i.imgur.com/01xBosX.png)

**Comment by sjmulder** [comment]
Using whatever the latest sc-im package is on FreeBSD, I experience the same. Suspending puts the shell prompt wherever my cursor happened to be, and resuming doesn't refresh the screen either.

In addition to the above, even after refreshing the screen following suspension, I don't get a visible cursor in my shell.

I don't usually have trouble with other programs, e.g. vim, less, etc.

**Comment by whereswaldon** [comment]
I adore `sc-im`, but I also have this problem. Other ncurses applications handle it (C-Z then `fg`) fine. I believe that the signal that is sent by the `fg` command is SIGCONT, though I don't know much about the semantics of it. I would imagine that it would suffice to create a SIGCONT handler that automatically redraws the screen, but I'm not sure.

**Comment by andmarti1424** [comment]
If that is the case it would be easy to fix!

**Comment by andmarti1424** [comment]
Please update to latest commit in freeze branch and try this!!

**Comment by sjmulder** [comment]
No dice yet for me on FreeBSD:

![suspended](https://user-images.githubusercontent.com/50692/33486518-ab24eee0-d6aa-11e7-9c0e-9355fb937165.PNG)

On 87242d8a8e4fdbd621f7dafcec5c17b4a95624b4

**Comment by andmarti1424** [comment]
Try resuming..

**Comment by sjmulder** [comment]
Typing `fg`<kbd>ENTER</kbd> in this situation did restore the screen.

However, if I first reset the screen with `clear`<kbd>ENTER</kbd> or <kbd>Ctrl+L</kbd> and then type `fg`<kbd>ENTER</kbd> again, the shell only prints `scim` and nothing else happens. When I then press <kbd>Ctrl+L</kbd><kbd>ENTER</kbd> again, scim reappears.

**Comment by whereswaldon** [comment]
@andmarti1424 Thanks, it does resume cleanly for me on Ubuntu 17.10!

However, when I suspend it in the first place it doesn't leave the terminal in a usable state. When I press `C-Z`, it doesn't clear the screen and my terminal emulator's cursor is invisible. I can resolve this by typing `reset`, so it's workable in its current state. Should I open a separate issue about this? It's not quite the same problem. I don't think that this behavior is new either, I just notice it more because I actually use `scim` with suspend/resume job control now.

**Comment by andmarti1424** [comment]
It wont be neccesary. I will try to fix it this afternoon.

**Comment by andmarti1424** [comment]
Could you please try again?!

**Comment by whereswaldon** [comment]
@andmarti1424 Works like a charm, thank you so much!

**Comment by andmarti1424** [comment]
@jimu? @sjmulder ?

**Comment by jimu** [comment]
The issue is fixed for me.  Suspend and resume work great - just like vim.

Thank you!

A few loose ends:

1) `make` reports:

```dep_graph.c: In function ‘EvalBottomUp’:
   dep_graph.c:526:9: warning: variable ‘evaluated’ set but not used [-Wunused-but-set-variable]
     int evaluated = 0;
         ^
```
2) version unchanged:
````
    > scim --version
    Sc-im - version 0.6.5
````

3) scim starts with "syntax error" on the second row

![scim starting screen](https://i.imgur.com/Fwfhohd.png)

4) scim --version outputs "syntax error"

![scim --version](https://i.imgur.com/2effVQa.png)

**Comment by andmarti1424** [comment]
I dont know about that "syntax error". I dont have that problem. Anyone else have that?
The version is still the same, yes. Didnt change the version number.

**Comment by jimu** [comment]
It seems i had an invalid line in my `.scimrc` file.  My mistake.

Perhaps we could change the error message from `syntax error` to something like this?
```
syntax error in ~/.scimrc on line 1
````

**Comment by andmarti1424** [comment]
That is not possible since thats a parser error and dont know the caller (in this case (.scimrc)
in other cases could be another file, or just user input, or may be script!

**Comment by sjmulder** [comment]
Thanks, works for me too. There is one small quirk: the prompt is printed halfway down the line, perhaps the cursor column needs to be reset or such?

![schermafbeelding 2017-12-02 om 09 52 24](https://user-images.githubusercontent.com/50692/33513622-a5af5f1c-d746-11e7-869f-4d626c83e512.png)

**Comment by andmarti1424** [comment]
@sjmulder, whats shown in your picture shouldnt happen. It should clean the sc-im spreadsheet and leave everything black (or your terminal background color) Whats your OS? You have latest ncurses or it is old?

**Comment by sjmulder** [comment]
That's what happens if I launch sc-im, then immediately suspend.

I'm using almost up-to-date FreeBSD, with system libraries, except libxslwriter which comes from a package:

    $ uname -rs
    FreeBSD 11.1-RELEASE-p4

    $ ldd scim
    scim:
            libncursesw.so.8 => /lib/libncursesw.so.8 (0x800887000)
            libm.so.5 => /lib/libm.so.5 (0x800ae5000)
            libxlsxwriter.so.0 => /usr/local/lib/libxlsxwriter.so.0 (0x800d10000)
            libthr.so.3 => /lib/libthr.so.3 (0x800f4e000)
            libc.so.7 => /lib/libc.so.7 (0x801176000)
            libz.so.6 => /lib/libz.so.6 (0x80152e000)

To build, I have added the following to the top of the Makefile:

    CFLAGS  += -I/usr/local/include -I/usr/include
    LDFLAGS += -L/usr/local/lib     -I/usr/lib
    LDLIBS  += -lncursesw

Other programs like vim are using the same ncurses version.

**Comment by sjmulder** [comment]
I did some further testing:

 * On FreeBSD, all curses program stay in scrollback on suspension. So whether _It should clean the sc-im spreadsheet and leave everything black_ depends on the system.

 * Suspending scim on FreeBSD / sh puts the prompt on the middle of the line (as shown in the screenshot) but otherwise works.

 * Suspending scim on Ubuntu / bash works well.

 * Suspending scim on Ubuntu / **sh** puts the prompt on the middle of the line but also unresponsive to any input so I have to forcefully close the terminal. Blindly typing `fg` <kbd>Enter</kbd> didn't help 
either.

It seems then that the problem is somehow specific to the combination of scim and sh. (Although I have not tested any combinations other these listed.)

**Comment by andmarti1424** [comment]
@sjmulder, please take note that VIM does not use ncurses. Yes, I believe the shell has its own interpretation of the SIGTSTP signal.. Regardin sc-im ncurses is paused and resumed as it should acording to ncurses documentation. I believe there is nothing more we can do about this inside sc-im.

**Comment by sjmulder** [comment]
The vim binary I use is linked against ncurses but maybe it's not used for the UI. In any case, the terminal locking up completely can hardly be proper behaviour, not? It's easy to reproduce on Ubuntu:

    bash$ sh
    $ ./scim
    ^Z
    <type anything>

**Comment by andmarti1424** [comment]
It sure should not lock the terminal. What I say is that is probable has nothing to do with scim. I believe its more a shell issue. That steps to reproduce it, do not fail in my arch instalation. Just to see if anything changes..could you please try the same steps with mocp (moc package) or any other ncurses app?

**Comment by sjmulder** [comment]
With `top`, which uses ncurses:

    /usr/bin/top:
            libncursesw.so.8 => /lib/libncursesw.so.8 (0x800830000)

It works well:

    [1] + Suspended               top
    $

Again, this doesn't clear the screen entirely on my system, by design, but the prompt works properly.

I find it hard to believe that both FreeBSD's `sh` and Ubuntu's `sh` are broken.

**Comment by andmarti1424** [comment]
If it locks the terminal thats a behaviour of not reseting ncurses before suspending. Perhaps it uses another signal? Its hard to me to analyse this since I dont have freebsd and ubuntu right now. Could you do a simple C program and see whats the signal send by the OS when you press ctrl+z? 
SIGSTOP? SIGTSTOP? I am current catching the latest. May be it should caught both.

**Comment by andmarti1424** [comment]
Perhaps both SIGSTOP and SIGTSTP should be caught. Anoyher test in your system would be replacing SIGTSTP with SIGSTOP and see if the behavior is the same..

**Comment by andmarti1424** [comment]
@sjmulder , could you test the above? thanks!

**Comment by sjmulder** [comment]
@andmarti1424 I can't do such testing right now, sorry. If it helps, this is the control mapping:

    $ stty -a
    ...
    cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
            eol2 = <undef>; erase = ^?; erase2 = ^H; intr = ^C; kill = ^U;
            lnext = ^V; min = 1; quit = ^\; reprint = ^R; start = ^Q;
            status = ^T; stop = ^S; susp = ^Z; time = 0; werase = ^W;

**Comment by sjmulder** [comment]
Ubuntu’s `signal(7)` says: “SIGSTOP cannot be caught, blocked, or ignored” hence I doubt that’s the issue.
