### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [andmarti1424/sc-im#282]
I suggest to reuse a higher level build system than [your current make script](https://github.com/andmarti1424/sc-im/blob/eb807201c320d1991203e1bf9d98c92b0fc0afad/src/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
- [CMake](https://cmake.org/ "Building software with CMake")
- [Autotools](https://www.gnu.org/software/autoconf/autoconf.html#introduction "Building software with Autoconf")

**Comment by andmarti1424** [comment]
if these are still compatible with other BSD systems.. could be. pull requests are always welcome.

**Comment by elfring** [comment]
- Does [a tool like “autoscan”](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
- How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.12/manual/cmake-generators.7.html#cmake-generators "Listing of CMake generators")?

**Comment by andmarti1424** [comment]
How do you think about to support more development environments by the reuse of build system generators? -> may be if this project becomes bigger, and more developers work in sc-im..

**Comment by andmarti1424** [comment]
Does a tool like “autoscan” show any software dependencies that you find worth for further considerations? -> same. may be if the project becomes bigger and more dependencies have to be resolved..

**Comment by vanrein** [comment]
CMake is excellent for portability to BSD and usually even Windows.  It is much easier to use than autotools, for developer and builder.  The `ccmake` command offers a TUI or GUI in which configuration options are shown and easily edited.  This is similar to your instruction of editing `src/Makefile`, but the flow is the common one for CMake.

Your `src/Makefile` almost reads like a CMake file, and the two are just as easy to maintain.  Are you still open to such a pull request, as you said when this issue was still open?
