### ISSUE TITLE
Unbound keys disable bound keys in normal mode

### ISSUE THREAD

**Issue by taylor1791** [andmarti1424/sc-im#289]
I installed sc-im v0.7.0 using homebrew. Whenever I press ? in normal mode, I get a question mark in the upper left corner. At this point, most keys do nothing including motions. When I press control 2-4 times, normal behavior returns.

I believe that all non-bound keys have the same behavior. Can you tell me if this is expected? If so, is there a setting to let sc-im swallow the unbound key?

**Comment by waynr** [comment]
@andmarti1424 
So I accidentally press 'i' in normal mode because of my muscle memory from using vim and this program having vi-like key mappings and conceptual modes. I understand the vi-like key mappings and conceptual modes may just be coincidental and that this is its own program. But surely there is a way for the program not to get stuck in "waiting for command mode" (with no discernable way for me to actually enter commands without first pressing ESC and entering actual command mode using `:`) just because I accidentally press an unbound key. Is there a way to disable that behavior?

To be clear, this is what happens for me:

* in normal mode, i accidentally press an unbound key
* the `?` appears in the upper right corner of the screen
* i try typing anything, nothing happens. none of the keys i type are echoed anywhere on the screen as they would be had i pressed `:` (eg to write to a file with `:w filename`).
* if i wait 3 seconds, the question mark goes away

Is this really expected behavior? If so, what should I be doing when that question mark appears other than to waste finger motion pressing `ESC`? Why is this behavior not called out explicitly in the `:help`?

Is this behavior unexpected? If so, do you know how to fix it? I understand if you don't have the time, but if there is a simple configuration setting or a simple bug fix I can submit I would really like to contribute.

To be clear, I think the idea of an terminal spreadsheet editor is awesome and this program gives every appearance of being exactly what I want. But if I am expected as a new user to develop perfect muscle memory right away in order to use it without fumbling into this apparently do-nothing mode, then it's practically a non-starter.

Thanks for your time and consideration!
