### ISSUE TITLE
Example color configuration for a light theme

### ISSUE THREAD

**Issue by evmorov** [andmarti1424/sc-im#297]
Currently scim looks like that in my terminal:

![image](https://user-images.githubusercontent.com/1059480/48400837-875cf080-e738-11e8-8003-69a68e24bf45.png)

I've seen in README that I can configure it. I don't really want to tweak it really well and spend much time. Can someone give me an example of configuration for a light theme so at least I can see text I'm typing?

**Comment by andmarti1424** [comment]
Hello. Have you check :cellcolor and :color examples in the
[doc file](https://raw.githubusercontent.com/andmarti1424/sc-im/freeze/src/doc) ??

**Comment by evmorov** [comment]
Looks like it will take some time to define it all the keys and values. I'd rather have a full example to be able to try the product. If there is no so I'll try to do that later. Thanks

**Comment by jnduli** [comment]
I use solarized light theme and have a similar problem to the above mentioned. Adding the following lines to the ~/.scimrc file helps:

```
color "type=INPUT fg=BLACK bg=DEFAULT_COLOR"
color "type=NORMAL fg=BLACK bg=DEFAULT_COLOR"
color "type=WELCOME fg=BLACK bg=DEFAULT_COLOR"
color "type=CELL_SELECTION_SC fg=WHITE bg=BLACK"
color "type=MODE fg=BLACK bg=DEFAULT_COLOR"
```

**Comment by hfel** [comment]
I would like to have a "default" light theme as well, as my light X colorscheme is messing it up.

**Comment by akkartik** [comment]
I have this problem as well, and while I started out with a light colorscheme, that doesn't seem to be the culprit. Here's my baseline state with a temporary dark colorscheme, after clearing out all my shell configuration.

<img width="969" alt="0" src="https://user-images.githubusercontent.com/3161/80563901-49da3a80-89a1-11ea-84fc-ef852f79f1b5.png">

When I hit `<Enter>`, here's what I see.

<img width="1049" alt="1" src="https://user-images.githubusercontent.com/3161/80563962-6b3b2680-89a1-11ea-9ab4-5006a9a2d2f0.png">

If I type `:help`, I can see what I type. (This doesn't happen with a light background.) So far, so good.

<img width="1276" alt="2" src="https://user-images.githubusercontent.com/3161/80564100-bce3b100-89a1-11ea-9488-d25148a91a4a.png">

However, when I hit `<Enter>`, this is is what I see.

<img width="1256" alt="3" src="https://user-images.githubusercontent.com/3161/80564126-cb31cd00-89a1-11ea-85c0-de3a563d5493.png">

I also tried @jnduli's suggestions above, but the final screenshot above didn't change. (I have a bootstrap problem here since it looks like the documentation for colors might be mostly in the online help system, but I can't seem to find any way to read it 😄)

Any guidance or ideas most appreciated. I'd be happy to answer any follow-up questions or try out any commands you suggest.

**Comment by sisrfeng** [comment]
I hate dark theme!!!!!!!!!!!!!!!

**Comment by andmarti1424** [comment]
> I hate dark theme!!!!!!!!!!!!!!!
Do not feel alone. A lot of people do.

**Comment by sisrfeng** [comment]
![image](https://user-images.githubusercontent.com/53520949/193839828-c405c40d-b975-4382-a552-99d63b1b6449.png)

my config:

```
color   "type=INPUT              fg=BLACK bg=DEFAULT_COLOR"
color   "type=NORMAL             fg=BLACK bg=DEFAULT_COLOR"
color   "type=CELL_SELECTION_SC  bg=GREEN     fg=BLACK"
color   "type=MODE               fg=BLACK bg=DEFAULT_COLOR bold=0"

# prince of persia theme, 删掉了对light theme不友好的, (被上面的代替了)
# green和yellow反了
color   "type=DEFAULT             fg=BLACK     bg=DEFAULT_COLOR"
color   "type=HEADINGS            fg=BLACK     bg=YELLOW          bold=0"
color   "type=HEADINGS_ODD        fg=BLACK     bg=YELLOW          bold=0"

color   "type=GRID_EVEN           fg=WHITE     bg=DEFAULT_COLOR"
color   "type=GRID_ODD            fg=WHITE     bg=DEFAULT_COLOR"

color   "type=WELCOME             fg=YELLOW    bg=DEFAULT_COLOR   bold=0"
color   "type=CELL_SELECTION      bg=BLACK     fg=WHITE           bold=0"
color   "type=NUMB                fg=CYAN      bg=DEFAULT_COLOR"
color   "type=STRG                fg=MAGENTA   bg=DEFAULT_COLOR   bold=0"
color   "type=DATEF               fg=YELLOW    bg=DEFAULT_COLOR"
color   "type=EXPRESSION          fg=RED       bg=DEFAULT_COLOR"
color   "type=INFO_MSG            fg=CYAN      bg=DEFAULT_COLOR   bold=1"
color   "type=ERROR_MSG           fg=CYAN      bg=WHITE             bold=1"
color   "type=CELL_ID             fg=BLACK     bg=DEFAULT_COLOR   bold=1"
color   "type=CELL_FORMAT         fg=RED       bg=DEFAULT_COLOR"
color   "type=CELL_CONTENT        fg=CYAN      bg=DEFAULT_COLOR   bold=1"
color   "type=CELL_ERROR          fg=RED       bg=DEFAULT_COLOR   bold=1"
color   "type=CELL_NEGATIVE       fg=GREEN     bg=DEFAULT_COLOR"

# vim:ft=conf
```
