### ISSUE TITLE
Force reload of current opened file

### ISSUE THREAD

**Issue by divramod** [andmarti1424/sc-im#322]
Hey, 

i really like sc-im! Thx for the awesome work!

on mobile i work in termux (where i have sc-im installed also) and sync my files via syncthing and really like to work that way with vim.

now, i want to ask if it is somehow possible, to trigger a automatic redraw/reload of the currently open sc-im file when it has changed on the filesystem. 

by doing so, i could have a basic version of the really nice google spreadcheat sync function.

has anyone any idea on how to achieve this with the currently implemented functions in sc-im?

thx again for the awesome work!

**Comment by mschilli87** [comment]
@divramod: Not a full solution but if you find a way to trigger the refresh from outside (e.g. by a signal), you could use [entr](http://eradman.com/entrproject/) for the watching.

**Comment by divramod** [comment]
hey @mschilli87,

thx for the hint!

Do you have a link to the docs where something like that or the direction you intend are explained?

Do you have an idea how i can send a redraw signal to sc-im?

I am familiar with entr and could think of using it.

thx in advance!

**Comment by mschilli87** [comment]
No. I'm not familiar enough with sc-im to tell if that's possible.
I just wanted to point out that instead of adding code that watches files and updates, implementing signal handling would be enough to get this working (`entr` could simply trigger `kill -s USR1`) and with some configuration option (so `USR1` can mean redraw for your use case, but other things if wanted) this would open the door for many more features without changing sc-im again.

**Comment by andmarti1424** [comment]
Sending SIGWINCH signal would make redraw entre window..

**Comment by Erikrian-Koira** [comment]
## *
Hello, @divramod, since you succeeded in installing SC-IM on termux, I would like to ask some quetions about the steps:
1. Could you tell me what tools were used to compile SC-IM?
 * (Actually, I have tried Clang+Bison+Ncurses to compile SC-IM on Termux, but the *.o files could not be linked together finally. I feel puzzled for this.)
2.  If it is convenient for you, could you send me the binary file which can run on Termux?
## PS:
I installed SC-IM successfully on my x86-64-Debian computer, and it works well. Thanks for @andmarti1424 and your help.

**Comment by divramod** [comment]
hey @Erikrian-Koira 

i installed it with:

```
pkg install unstable-repo
pkg install sc-im
```

**Comment by Erikrian-Koira** [comment]
Thanks for your reply, @divramod.
However, there exists a strange problem on the Termux: It cannot open existing files.
**----------------------------------------------------------------------------------------------------------**
If there is a file named "Eng.csv", and I typed:
```
scim Eng.csv
```
The SC-IM lauched without opening the "Eng.csv"...
Then, I typed in SC-IM:
```
:load Eng.csv
```
SC-IM will give me an error message:
```
Failed Expanding Filepath
```
How to open file on Termux SC-IM?

**Comment by andmarti1424** [comment]
@divramod sorry.i misunderstood what you where asking. I thought you wanted to trigger UI refresh. What you need is a good idea. It could be handled with a signal..

**Comment by andmarti1424** [comment]
or with :edit just like in vim.

**Comment by andmarti1424** [comment]
you can use `:load file.csv` and it will be reloaded
