### ISSUE TITLE
Gnumeric opens sc-im file as text

### ISSUE THREAD

**Issue by Amooti73** [andmarti1424/sc-im#338]
When I try to open a file saved with sc-im in gnumeric, it opens as a text file not a spreadsheet.  However, if I open the same file in sc and save it with a new name, gnumeric recognizes it as a spreadsheet. I am using gnumeric 1.12.35 in Ubuntu 18.04 and sc-m version 0.7.0.

It is a bit mysterious because either file can be opened with vim and they appear the same, but there must be a difference.

**Comment by singpolyma-shopify** [comment]
I am willing to guess that the difference is that `sc-im` files cannot by default be detected as sc files by the `file` command.  This is because the default `file` command magic for determining if something is an sc file, is to look for the word "Spreadsheet" that is in the same position in every file created by sc, due to this line being present:

    # This data file was generated by the Spreadsheet Calculator.

sc-im files rather say "by SC-IM" rather than "by the Spreadsheet Calculator"

Either better magic rules need to be proposed and adopted, or else SC-IM could say "by the Spreadsheet Calculator (Improved)" or similar to  be compatible with current file magic.

Or you can just edit the file yourself so it will be recognized :)

**Comment by Amooti73** [comment]
Thanks @singpolyma-shopify  for your explanation which makes sense! Since there are simple workarounds, I guess the issue can be closed!  Just as a "by the way", when I tested your suggestion of editing the file saved with sc-im, I found that "the" must be included when you edit!
