### ISSUE TITLE
Provide better computer readable export format

### ISSUE THREAD

**Issue by gnusupport** [andmarti1424/sc-im#348]
It would be better if there is export in some more sure well known structure of data. Now is format only sc-im related. I would prefer better format. Maybe XML or Lisp structure, Json, something like  that.

**Comment by zvezdochiot** [comment]
@717g301github say> Maybe XML

+

GZIP XML = gnumeric.

**Comment by 717g301github** [comment]
aha is it implemented already?

**Comment by zvezdochiot** [comment]
@717g301github say> aha is it implemented already?

No from the word "nothing" This is my wish, added to yours.

**Comment by alexandre-mbm** [comment]
I think that SC-IM must be minimalist. The project on Github is stuck because it was overloaded with non-essential demands like this.

The main concern should be the absence of bugs!

The code is freezed...

I heard that Gnumeric can import *.sc files. That should suffice! The SC-IM does not need to become a file exporter. It will never be widely adopted. It is just a minimalist tool. And as such it should work well, without errors.

I vote to archive this issue.

**Comment by andmarti1424** [comment]
Yes. Please open a discussion for this.

**Comment by gnusupport** [comment]
You have expanded `sc` to `sc-im` so `sc` was small already and was enhanced by you, thank you. You have no time alright. I can make convertor somehow.

**Comment by andmarti1424** [comment]
You can export formulas to a csv file if you save them as text.
But please open a discussion so everyone can vote/express on this topic.
