### ISSUE TITLE
Any way to enter greek symbols like Vim's digraphs?

### ISSUE THREAD

**Issue by earthshrink** [andmarti1424/sc-im#356]
The following already works:
```
label C1 = "Δω = -βωr/c"
leftstring C3 = "ψ(x)"
```
That is, sc-im displays these formula labels nicely. However, there is no easy way to input them. I tried declaring
```
imap "<C-k>b*" "β"
```
etc. but `:showmaps` shows the result strings as empty, and typing `<Ctrl-k b*` produces simply the label `b*`. It also does not take `Ctrl-Shift-u 03c0`, which should have produced `π`, and works in Gnumeric.

**Comment by earthshrink** [comment]
I have a basic implementation, for just the Greek letters.

**Comment by andmarti1424** [comment]
This you have done is great! Thanks for your work.
If you can, could you please add it to the doc file explaining how to input them? THANKS!

**Comment by Kornwaliusz** [comment]
I have similar problem witch polish characters: ą, Ą, ć, Ć  
rigth alt + a → „ą”  
right alt + shift + a → „Ą”  
rigth alt + c → „ć”  
right alt + shift + c → „Ć”  
  
In imput mode in sc-im:  
ą → moves one character forward  
Ą → moves one character backward  
ć → backspace (deletes character)  
Ć → moves to the beginning  
  
In scimrc when i remap (input mode) „ć” it changes behavior of backspace.
For example when i remap „ć” to „c”, backspace inputs „c” instead of deleting character.
  
I tried editing file „digraphs.c”.
I changed „∞” for „ć”.
And now ctrl + k + 0 + 0 is backspace.
It deletes character, instead on inputting „ć”.
  
Sc-im is able to handle all polish characters.
I created a file with them. 
When i opened the file, they worked fine.
I can yank and paste them.
I just can not input them.
  
@earthshrink do you know what the fix might be?
