### ISSUE TITLE
conform to xdg specification

### ISSUE THREAD

**Issue by rnxpyke** [andmarti1424/sc-im#358]
The application should follow the xdg base dir standard. See [freedesktop.org](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) or the [arch wiki](https://wiki.archlinux.org/index.php/XDG_Base_Directory).

This means that the following locations should be used:
- `$HOME/.sc-iminfo` becomes `$XDG_CACHE_HOME/scim/info`
- `$HOME/.scimrc` becomes `$XDG_CONFIG_HOME/scim/scimrc`
- `$HOME/.scim/module` becomes `$XDG_DATA_HOME/scim/module`
- `$HOME/.scim/lua` becomes `$XDG_DATA_HOME/scim/lua`

If one of these variables is unset, the default should be respected:
- `XDG_DATA_HOME="$HOME/.local/share"`
- `XDG_CONFIG_HOME="$HOME/.config"`
- `XDG_CACHE_HOME="$HOME/.cache"`

**Comment by nickspoons** [comment]
PR #337 does this to an extent, but doesn't check for environment variables as it should.

**Comment by bentitmus** [comment]
In addition it doesn't use it for `plugin_exists` which just checks for files in `~/.scim`. In fact, because `plugin_exists` looks for additional configuration files, `scimrc` should really be contained in `$XDG_CONFIG_HOME/scim/scimrc` rather than `~/.config/scimrc` which is where it is located at the moment.

**Comment by dther** [comment]
Made a patch for this! Check the above pull request.
