### ISSUE TITLE
I cannot open xls files

### ISSUE THREAD

**Issue by sourjyo0** [andmarti1424/sc-im#406]
"XLS import support not compiled in "is the error message
Built it from yay.
xlsx works fine.
Any idea how to fix this?

**Comment by sourjyo0** [comment]
Also how do you jump between multiple sprreadsheets in the same xlsx file?

**Comment by andmarti1424** [comment]
Please install libxls for xls support. (Dont recommend it since its obsolete).
You cant move around between sheets sadly.
Right now, SC-IM only supports one file opened at a time.
You can open a different sheet other than the first one though. You can use the --sheet parameter.  Please check out doc file.
