### ISSUE TITLE
SC-IM on Windows

### ISSUE THREAD

**Issue by denisov0gleb** [andmarti1424/sc-im#460]
First of all, thank you for your project, it looks nice!

### Question:
Is it possible to build SC-IM on Windows?

First look to **Makefile** shows that it is strongly depend on *nix architecture.

Also there are not listed any *Dependencies* in **Readme** file :((

**Comment by andmarti1424** [comment]
Basically it requires ncurses.
Havent tried it since I am not a Windows user.
It would probably build successfully with minimum changes.
If you manage to build it please share those changes so I can merge them in  the project and give SC-IM full WIndows support.

**Comment by Virgilio-AI** [comment]
I coul't is, I tried using ubuntu from the microsoft store but making the file leads to and error, if somebody manages to do it please let me know

**Comment by andmarti1424** [comment]
What's your OS? Ubuntu or Windows? Did you download ncurses?

**Comment by Virgilio-AI** [comment]
my os is windows, for me to use ncurses I tried using the linux ubuntu terminal in available in the microsoft store, I manage to install all the requirements but making the file fails ( I believe since it is only a terminal of ubuntu and literally you only have one folder and would have to create the full system from scratch)
I think the main problem and the reason I was not able to do it from a simple power shell is because I didn't found any information about how to install ncurses and bison

**Comment by Virgilio-AI** [comment]
ncurses is not avaliable for windows 10

**Comment by andmarti1424** [comment]
Mmm. Try cygwin perhaps?

**Comment by OliverLew** [comment]
If you are using Windows WSL, then isn't that Ubuntu already a complete Linux system. Have you tried to install ncurses and bison just like on *nix platforms with (within the ubuntu terminal you mentioned)
```
sudo apt update
sudo apt install ncurses bison
```
or something similar?

**Comment by Virgilio-AI** [comment]
@OliverLew, yes that's the first think I did and it worked, but I belive that terminal is not very well integrated into the sistem so i doesn't let's me navigate my computer files and store new, obviously it doesn't alouds to compile files that are inside my sistem, I believe is just an emulation of linux. if somebody know's what to do you can let me know. I am currently using the ubuntu app that I found in the microsoft store, I could use any suggested ones to get all running. and cygwin I believe doesn't alouds ncurses

**Comment by Virgilio-AI** [comment]
@OliverLew hello, yes you were right. I found out the folder that cointains all windows data. I think I am almost there. if you have more experience making proyects using make perhabs you could help me with this error message 
![image](https://user-images.githubusercontent.com/59902976/111056641-3d8a8f00-8446-11eb-8bc1-f868905023ee.png)
I have already installed ncurses, bison, make, gcc. even the optionals. it says undefined I have already included -lncurses at the end of the compile command and still don't works. I am pretty shure that I have ncurses working because I compiled and runned a single test file. so any suggestions?

note: I will gladly share the changes I made to make it work in windows properly once I get it to work :)

**Comment by andmarti1424** [comment]
It's not linking to ncurses properly. Try with - lncursesw

**Comment by OliverLew** [comment]
> doesn't let's me navigate my computer files and store new,

@Virgilio-AI that seems the only problem here. I guess it's something like you downloaded `sc-im` files on Windows and couldn't access those files in the Ubuntu subsystem?

Actually you can do everything just in Ubuntu, download(clone) source files with `git`.

Or if you want to send files from Windows to Ubuntu, a quick search leads me to this:
https://www.howtogeek.com/426749/how-to-access-your-linux-wsl-files-in-windows-10/

Anyway, the problem is not related to sc-im.

**Comment by andmarti1424** [comment]
Did you try it with cygwin @Virgilio-AI ?

**Comment by andmarti1424** [comment]
btw, old SC used to work on ms-dos.. Dont know how the ncurses stuff was handled..

**Comment by andmarti1424** [comment]
If you managed to build it please dont forget to add a wiki explaining the steps done! Thanks!

**Comment by hamza-tam** [comment]
@andmarti1424, I have been using sc-im on windows with WSL for the past year and it works perfectly fine. Building on WSL with Ubuntu requires to follow exactly the same steps as building a machine with Ubuntu installed.
