### ISSUE TITLE
can't save xlsx

### ISSUE THREAD

**Issue by arvyanh** [andmarti1424/sc-im#467]
open the xlsx after saving using`:wq` will show nothing.   (I could open the .xlsx save by other programs)

Using something like gnumeric warns about `Unhandled directive: 'mark' `
Using vim to open is shows:
```
# This data file was generated by the Spreadsheet Calculator.  That is SC-IM, the improved one!
# You almost certainly shouldn't edit it.

mark a A-1
mark b A-1
mark c A-1
....
```
Which I suppose is the `mark` gnumeric warns.

Is it a bug or the issue with xlsxlibs?

**Comment by Ethanol6** [comment]
Yes, I have noticed the same behaviour. If I load an .xlsx file and then save it with :w the file is overwritten with .sc file type information but still keeps the .xlsx file extension. Then, loading the .xlsx file in SC-IM displays a blank spread sheet, but renaming the file manually with .sc file extension and loading it in SC-IM will open the spreadsheet as it should.

Opening a spreadsheet in the SC-IM .sc format with any other editor, Gnumeric or LibreOffice Calc will display that same warning and in LibreOffice shows the same text you posted down the first column of the spreadsheet.

I have been using the export :e! command to save these files in .xlsx format instead of :w 

It's kind of a bug I suppose. The :e xlsx command explicitly invokes the xlsxlibs to write the file but the usual :w write command doesn't seem to notice this file extension and defaults to .sc file type write behaviour. The :w command works as expected with all the other file types though, txt, csv, etc.

**Comment by reportaman** [comment]
@Ethanol6 @arvyanh I filed this issue yesterday... https://github.com/andmarti1424/sc-im/issues/493. There seems to be no commit after Sep 4, 2020. Not sure what the direction is of this wonderful project.

**Comment by andmarti1424** [comment]
Hello. This is correct.
:w command always saves is sc format.
To save in csv or xlsx or tab.. you have to use the export command   :e
