### ISSUE TITLE
Get current row or cell value? 

### ISSUE THREAD

**Issue by BlakeWeissman** [andmarti1424/sc-im#477]
If this feature doesn't exist already would it be possible to implement a function that gets the current row/column value? Ex using `@ccol` on cell D2 would return "D"  or using `@crow` on C5 would return "5". I'm aware of `@frow` and `@fcol` however these require a parameter which defeats the purpose of what I'm going for.

**Comment by reportaman** [comment]
@BlakeWeissman If you trying to evaluate a column/row/cell value in relation to other columns/row/cel then try: ``@coltoa(@mycol)``, and ``@myrow`` in an expression, and it will evaluate correctly. For instance, in the following expression: ``=@nval(@coltoa(@mycol-1),@myrow)*1000/255`` will get the numeric value of adjacent cell in previous column, multiply it by 1000 and divide it by 255. Copying this expression in the entire "current column" will evaluate the entire column based on the values in previous column. I learnt it the hard way, the documentation should have one such example that shows how one can do expressions relative to current cell position.

**Comment by andmarti1424** [comment]
@BlakeWeissman was @reportaman useful to you?

**Comment by reportaman** [comment]
@BlakeWeissman At the time I made that last comment, sc-im had a bug that prevented ``\@coltoa(@mycol)<CR>`` to print D when entered in cell D2. Now that is fixed, so it does exactly what you want ``@ccol`` to do. For ``@crow`` if you want numeric value then do ``=@myrow``, it will put numeric value 5 when run from cell C5. Or if you want a string value, then convert number to string and enter an expression like this ``\@fmt("%.f",@myrow)``, it will put string "5" instead of number 5 in cell C5.

**Comment by andmarti1424** [comment]
Yes, actually with \ followed by "
that is \"@fmt..

**Comment by reportaman** [comment]
@andmarti1424 Btw, as a sidenote Filipe Miguel Tavares (GitHub user @fmt) might be receiving a lot of sc-im updates :) I tend to put sc-im commands that gave ``@`` in them as code ``@fmt``. Github markdown!!

**Comment by andmarti1424** [comment]
`@fmt` Roger that

**Comment by mycol** [comment]
Who disturbs my slumber?!
