### ISSUE TITLE
Why is there a limit of 1,048,576 rows?

### ISSUE THREAD

**Issue by pkillnine** [andmarti1424/sc-im#480]
It says in the Readme file "65.536 rows and 702 columns supported. (The number of rows can be expanded to 1.048.576 if wished).", why does it have this limit?

**Comment by andmarti1424** [comment]
Those are 2^16 and 2^20 values. Excel used to have that values as limit as well. Then switched to 2^20. Dont know which limit they have now.

**Comment by pkillnine** [comment]
So it's a limit in the xlsl format, and the limit is added to sc-im so the file it saves remains compatible with Excel?

**Comment by reportaman** [comment]
And what does it mean "The number of rows can be expanded to 1.048.576 if wished". Does the limit also apply to csv files? Any plans to change that, and apply it only to import/export of xlsx format?

**Comment by andmarti1424** [comment]
Does not matter if its csv, xlsx.. as long as gets memory allocat'ed 

You can test increasing it by changing this value in Makefile:
CFLAGS += -DMAXROWS=65536

I believe some UI problems would appear if passed 9.9 million rows though.
I know MS Excel had this limitation as well. Dont know in the last versions since its been years since I no longer use Excel.
