### ISSUE TITLE
slow when opening files

### ISSUE THREAD

**Issue by jedi2610** [andmarti1424/sc-im#499]
it takes a good 20 seconds to load a 450KB file. it is fast when opening smaller files (32KB). is this expected?

**Comment by andmarti1424** [comment]
Hello. What kind of file you are opening?
.SC, .CSV, .XLSX???

**Comment by jedi2610** [comment]
@andmarti1424 it's a csv file

**Comment by andmarti1424** [comment]
Is it possible for you to attach to this issue so I can test it? Or sending it to scim.spreadsheet@gmail...

**Comment by jedi2610** [comment]
ofc, here is a link to the file `https://ufile.io/mp41i1q3`

**Comment by andmarti1424** [comment]
It took a lot in my computer to open! This is a great file to test speed! The file is not too big.
It should open more quickly.

What it does is, for every cell it calls to the interpreter. And it seems that process is rather slow.

Of course it could be optimized, so a bunch of cells can be stored at the same time.
May be it can be done by row rather than by cell.

**Comment by andmarti1424** [comment]
@jedi2610 It would be ok if I upload the file to the repository so I can avoid losting it?

**Comment by reportaman** [comment]
On my system it took 15sec of user time for ``>> time sc-im train.csv``. As a UI advice, I could recommend something more... Load and display the cells that can fit the screen, and show a progress bar on top that hows percentage of lines loaded.

**Comment by andmarti1424** [comment]
You both have good computers. Mine took ages.

@reportaman both of that are a good idea as well!

**Comment by reportaman** [comment]
@andmarti1424 Yes I have the Apple Silicon M1 MacMini. It's very fast, among the fastest CPU performance/watt, and even raw sustained performance. It starts at $699, which is quite economical if you already have a screen, keyboard, and mouse. Its also dead silent, and for day-to-day tasks never heats up (mine remains 5-10C above room temperature the entire period it is ON, my past Intel CPU used to hover around 75C with fans turned while performing same activity). It's inbuilt application "Numbers" loads this csv file in under 3 first time it was able to load, and then 1-2 second after that (probably because things get cashed at some point). Though it did crash the very first time I tried opening it, never again though.

**Comment by jedi2610** [comment]
@andmarti1424 feel free to upload it to the repo

**Comment by jedi2610** [comment]
@reportaman nice idea. @andmarti1424 is that easy to implement?

**Comment by andmarti1424** [comment]
@jedi2610 The linerang is pretty doable.
the percentage I believe is not that easy since I read the file until EOF if I recall correctly.
I would have to read it twice (the first one to count the \n chars) and all to show the loading percentage..
The loading in background is a better idea IMO.

**Comment by jedi2610** [comment]
yeah it do be like that while writing programs in `C` lol. btw, this is such a great project and is underrated.

**Comment by andmarti1424** [comment]
Seems people do not use spreadsheets a lot anymore.

**Comment by reportaman** [comment]
@andmarti1424 In my engineering work people use spreadsheets a lot. I think this is the real problem: Unlike source code, spreadsheets that engineers create are frequently shared with management, and management people do not understand command line & are generally trained in excel. Also, people share and edit spreadsheets online. 

Where does sc-im standout? It's spreadsheet on steroids, given we can seamless integrate any functionality with lua interface among other things. The tools like Microsoft excel are limited by their closed nature, and are not so elegantly extensible. I think we need to take a step back and write a proposal for developer community so they understand what sc-im is meant for, and put that up on places like Patreon page for sc-im, etc Also, as a first lets have a standard way of naming it, I think dash in the name should be reconsidered...

**Comment by andmarti1424** [comment]
Hello. Could you please test this again?

**Comment by jedi2610** [comment]
did you update the package on aur?

**Comment by andmarti1424** [comment]
Nono. Just committed on github

**Comment by jedi2610** [comment]
okay I'll check it out

**Comment by jedi2610** [comment]
can confirm that it works perfectly fine. please do update the package in aur.

**Comment by andmarti1424** [comment]
Yes. My idea is to make a release in the next days (probably less than 2 weeks). Then the AUR maintainer can update it.

**Comment by jedi2610** [comment]
okay sounds good.
