### ISSUE TITLE
Hide (or Zap) only labels of selected cells

### ISSUE THREAD

**Issue by TiagoDillenburg** [andmarti1424/sc-im#536]
Hi, thank you for this awesome software. I would like to ask for a feature.
I couldn't find a way to only hide the labels of a selection of cells.

I've been using labels as a way to "mark" or identify what a cell value stands for in adition to row categories, for instance, temporary expenses during easter ("páscoa") or temporary expenses with bath towels ("toalhas").

![image](https://user-images.githubusercontent.com/13285472/113521982-91832200-9573-11eb-8265-c797ade585a0.png)

I would like to be able to toggle the visibility of these labels on and off, specially because the numeric values collapse underneath the labels when the column width is shrank.

![image](https://user-images.githubusercontent.com/13285472/113522087-546b5f80-9574-11eb-9109-0fedc5e9614e.png)

**Comment by andmarti1424** [comment]
Hello @TiagoDillenburg. Glad the software is useful for you.
It is for me.

The idea of having both labels and numbers in sc-im comes from old sc. I dont really like it much since its a little confusing and not that useful.

What you ask can be added though. Would like to know what other users think about it.

btw I am trying to leave the issues more for bugs rather than feature requests.
Please feel free to open a discussion for this feature request.

**Comment by andmarti1424** [comment]
Please feel free to open a discussion for this feature request, so others can give their opinion. Thanks.
