### ISSUE TITLE
segfault on save

### ISSUE THREAD

**Issue by riX2000** [andmarti1424/sc-im#58]
With the latest version, I'm getting segfaults on save.
I'm not sure what extra information you would need.

**Comment by andmarti1424** [comment]
This happen to you on any file you save? With any content? 
It's weird since the save routine was not modified. 

-------- Mensaje original --------
De: riX2000 <notifications@github.com> 
Fecha: 16/02/2016  8:33  (GMT-03:00) 
A: andmarti1424/sc-im <sc-im@noreply.github.com> 
Asunto: [sc-im] segfault on save (#58) 

With the latest version, I'm getting segfaults on save.

I'm not sure what extra information you would need.

**Comment by andmarti1424** [comment]
I know what it is. It only seems to happen when saving colors. Will fix it.

**Comment by riX2000** [comment]
Yes, saving a file without colors works.

**Comment by andmarti1424** [comment]
Please try updating to latest dev branch commit and try again to see if its fixed!
Thanks!

**Comment by riX2000** [comment]
Working!

**Comment by andmarti1424** [comment]
Both of the issues or just the one when saving files? Thanks! 

-------- Mensaje original --------
De: riX2000 <notifications@github.com> 
Fecha: 17/02/2016  8:33  (GMT-03:00) 
A: andmarti1424/sc-im <sc-im@noreply.github.com> 
CC: "Andrés M." <andmarti@gmail.com> 
Asunto: Re: [sc-im] segfault on save (#58) 

Working!

**Comment by riX2000** [comment]
Both :)
