### ISSUE TITLE
Insert/Command -> Visual Mode not working

### ISSUE THREAD

**Issue by ga47wot** [andmarti1424/sc-im#634]
The <C-v> command does not function while I am in the insert/command mode and want to switch to visual mode.

Secondly, the command remapping to a different key mapping using :cmap "<C-v>" "<C-s>" does not work as well. And also inserting this command in the ~/.confg/sc-im/scimrc file throws a syntax error when a new sc-im file is opened.  

 I have already removed the default terminal's text paste function mapped  to the <C-v> key to avoid any conflicts. I am using Ubuntu distro with WSL.

**Comment by 1dancook** [comment]
*sc-im version: 0.8.3-main*

I can confirm that `<C-v>` does not work as it is documented when in **Insert** and **Command** mode.  I have tried 3 different terminals on my mac. Inside and outside of tmux. What happens is basically nothing - sc-im persists in the current mode that it was.

**BUT!** I managed to install sc-im on my ipad in a linux (Alpine) emulator app and *it does work* there as documented.

There is something wrong, but not sure how to pin it down exactly since it is working.

### Using alternative mappings made it work
I added this to my scimrc and this makes it work:

```
imap "!:" "<C-v>"
vmap "O" "<C-o>"
vmap "K" "<C-k>"
```

So the problem seems to be that somehow scim is not getting the `<C-v>` / `<C-o>` / `<C-k>` key strokes. 

**Note**: other `control` commands work as expected on my machine - like `<C-r>`, `<C-k>`

---

@ga47wot an alternative method to getting a selected range is to use marks:

1. visual mode select what you want and do `ma` which will mark `a` as that range.
2. In insert or command mode you can use `<C-r>{mark}` to insert the marked range. So, `<C-r>a` to insert the range you marked with `a`. 

--- 

> Secondly, the command remapping to a different key mapping using :cmap "" "" does not work as well.

@ga47wot I'm confused about what you are trying to map with `:cmap "" ""`. Please explain a bit more.

**Comment by ga47wot** [comment]
Thanks for the suggestions and workaround.
