### ISSUE TITLE
Inserted cell not regarded in range

### ISSUE THREAD

**Issue by Eucyon** [andmarti1424/sc-im#642]
Use the following cells:

A0: 1
A1: 1
A2: @sum(A0:A1)

A2 shows the correct sum. If you change A0 or A1, the sum in A2 is correctly updated.

Now insert a row between A0 and A1 and put in a numeric value in the new A1, e.g. also 1. The sum in now A3 is not correctly recalculated, also not after changing the new A1.

After saving and reentering the sheet, it behaves correctly.

**Comment by andmarti1424** [comment]
Yes, indeed. You can press '@' to recalculate.
The problem seems to be in the insert_row not recalculating.

**Comment by andmarti1424** [comment]
Please update to latest commit on dev branch and retry. Thanks.

**Comment by andmarti1424** [comment]
@Eucyon could you test it?

**Comment by 1dancook** [comment]
*sc-im version: dev (3bda539)*

Works as expected on my machine.

**Comment by andmarti1424** [comment]
Thank you @1dancook

**Comment by Eucyon** [comment]
Sorry for answering late. Yes, works fine, thank you!

**Comment by xkcd386at** [comment]
I hesitate to open a new issue in case I goofed, but there is a corner case where this is not working for me (version 0.8.5), *and not even save/close/reopen helps* because the formula is not updated correctly.

(Another reason I didn't want to open a new issue is that one could also argue this is the correct behaviour!)

1. Enter A0, A1, A2 as 1,2,3
2. go to A3 and type `:fsum`; you get `@sum(A0:A2)` in that cell.
3. now go to A2 and type `or` (open new row after current row)
4. type in some number here
5. observe the new A3 still shows the old range (`A0:A2`)

If you add a new row after A0 or A1 it works fine; it's only the last row in the range that this does not work with.

My workaround is to insert a dummy row with all 0's in numeric columns, and making sure to add new rows *above* that.
