### ISSUE TITLE
Backspace not working in tmux

### ISSUE THREAD

**Issue by fedemp** [andmarti1424/sc-im#70]
Not exactly the same as https://github.com/andmarti1424/sc-im/issues/25

Backspace does not work if a launch scim under tmux on linux. `$TERM` is `tmux-256color`.

Used latest code from this repo.

**Comment by andmarti1424** [comment]
I always use it inside tmux.. What is your OS and tmux version?

**Comment by andmarti1424** [comment]
What is your OS and tmux version?

**Comment by fedemp** [comment]
Archlinux. Using tmux 2.2 (latest on stable). I have tried both the aur version and cloning this repo.

**Comment by JohnLunzer** [comment]
I'm on RHEL 6 with tmux 2.0. @andmarti1424 can you please give us some more details on your environment? I use xonsh as my shell, I've tried several $TERM values without success.

**Comment by andmarti1424** [comment]
Please check here: https://github.com/andmarti1424/sc-im/issues/25

**Comment by JohnLunzer** [comment]
I can confirm via `showkey -a` that my backspace key is 0x7f on RHEL 6. So I think a better way is needed to determine what BS is, what you have in macros.h at the moment isn't sufficient because 0x107 doesn't seem to be applicable to all Linux distros.

At the very least this needs to be at the bottom of the readme as a gotcha. sc-im is a great CLI app. I'd hate for people to abandon it because their BS key didn't work out of the box!

**Comment by andmarti1424** [comment]
Yes, perhaps it should. But I regularly use just one distro and do not know how others work regarding this issue. Patches are welcome though.
I updated the wiki yesterday adding this topic.
