### ISSUE TITLE
can not map <C-q> to ":cellcolor" function 

### ISSUE THREAD

**Issue by EdwardWong1994** [andmarti1424/sc-im#737]
Hi 

I try to map `<C-q> ` to a function `:cellcolor "bg=CYAN fg=BLUE"` using `vnoremap "<C-q>" ":cellcolor\"bg=CYAN fg=BLUE\"`, but it won't work. 
The below figure is the mapping result when i type `:showmaps`

 Can you give me some hints on this? Much thanks

![Xnip2022-09-02_10-21-40](https://user-images.githubusercontent.com/96438179/188045022-78242572-f02b-40f2-a0ed-d963005af90d.jpg)

**Comment by 1dancook** [comment]
It seems as though some CTRL+<something> combinations just don't work. I don't know if this is a bug type of issue or it may be because some key combinations are reserved for other things. Evidence for the latter is that I was able to get your formula working with <C-t> but not with <C-q> or <C-v>.

It looks like you are also be missing a space after `:cellcolor`. Compare:

- `vnoremap "<C-t>" ":cellcolor\"bg=CYAN fg=BLUE\"`
- `vnoremap "<C-t>" ":cellcolor \"bg=CYAN fg=BLUE\"`

---

FWIW in my config I have a number of text coloring and highlighting mappings. I use comma as a leader in vim so I use some easy to remember ways (for both normal and visual mode).

Works like this:


Leader (comma)   
\+ **h** = highlight _or_ **t** = text color   
\+ **y** = yellow, **b** = blue, **g** = green, etc.


I'll put them here if you care to adapt it or use it as is:

```
# Mappings for highlighting cells (changes background color)
nmap ",hy" ":cellcolor \"bg=YELLOW fg=BLACK\"<cr>"
vmap ",hy" ":cellcolor \"bg=YELLOW fg=BLACK\"<cr>"
nmap ",hr" ":cellcolor \"bg=RED fg=BLACK\"<cr>"
vmap ",hr" ":cellcolor \"bg=RED fg=BLACK\"<cr>"
nmap ",hb" ":cellcolor \"bg=BLUE fg=BLACK\"<cr>"
vmap ",hb" ":cellcolor \"bg=BLUE fg=BLACK\"<cr>"
nmap ",hg" ":cellcolor \"bg=GREEN fg=BLACK\"<cr>"
vmap ",hg" ":cellcolor \"bg=GREEN fg=BLACK\"<cr>"
nmap ",hm" ":cellcolor \"bg=MAGENTA fg=BLACK\"<cr>"
vmap ",hm" ":cellcolor \"bg=MAGENTA fg=BLACK\"<cr>"
nmap ",hc" ":cellcolor \"bg=CYAN fg=BLACK\"<cr>"
vmap ",hc" ":cellcolor \"bg=CYAN fg=BLACK\"<cr>"
nmap ",hw" ":cellcolor \"bg=WHITE fg=BLACK\"<cr>"
vmap ",hw" ":cellcolor \"bg=WHITE fg=BLACK\"<cr>"

# Mappings for coloring text (leader, (t)ext, (color)
nmap ",ty" ":cellcolor \"bg=DEFAULT_COLOR fg=YELLOW\"<CR>"
nmap ",tr" ":cellcolor \"bg=DEFAULT_COLOR fg=RED\"<CR>"
nmap ",tb" ":cellcolor \"bg=DEFAULT_COLOR fg=BLUE\"<CR>"
nmap ",tg" ":cellcolor \"bg=DEFAULT_COLOR fg=GREEN\"<CR>"
nmap ",tm" ":cellcolor \"bg=DEFAULT_COLOR fg=MAGENTA\"<CR>"
nmap ",tc" ":cellcolor \"bg=DEFAULT_COLOR fg=CYAN\"<CR>"
nmap ",td" ":cellcolor \"bg=DEFAULT_COLOR fg=DEFAULT_COLOR\"<CR>"
vmap ",ty" ":cellcolor \"bg=DEFAULT_COLOR fg=YELLOW\"<CR>"
vmap ",tr" ":cellcolor \"bg=DEFAULT_COLOR fg=RED\"<CR>"
vmap ",tb" ":cellcolor \"bg=DEFAULT_COLOR fg=BLUE\"<CR>"
vmap ",tg" ":cellcolor \"bg=DEFAULT_COLOR fg=GREEN\"<CR>"
vmap ",tm" ":cellcolor \"bg=DEFAULT_COLOR fg=MAGENTA\"<CR>"
vmap ",tc" ":cellcolor \"bg=DEFAULT_COLOR fg=CYAN\"<CR>"
vmap ",td" ":cellcolor \"bg=DEFAULT_COLOR fg=DEFAULT_COLOR\"<CR>"

```

**Comment by EdwardWong1994** [comment]
That is very kind of you to share your keybindings. thanks

**Comment by andmarti1424** [comment]
@EdwardWong1994 May be your terminal does not allow to use CTRL-q..
I dont see it reserved for its use on sc-im
