### ISSUE TITLE
install: /usr/bin/scim: Operation not permitted

### ISSUE THREAD

**Issue by incandescentman** [andmarti1424/sc-im#76]
I get errors when I try to make install. 

I'm on OSX El Capitan. 

I already did this: ```

    $ brew install ncurses
    $ brew link ncurses --force```

and I uncommented this line in Makefile:  
  
```MACOSX := -DMACOSX```

But I still get these errors:

```
~/Downloads/sc-im-dev-1/src (master *) $ sudo make install
Password:
install -d /usr/bin
install: chmod 755 /usr/bin: Operation not permitted
install scim /usr/bin/scim
install: /usr/bin/scim: Operation not permitted
make: *** [install] Error 71

```

Any suggestions?

**Comment by incandescentman** [comment]
Also, I did install ncurses. 
```

$ brew link ncurses
Warning: ncurses is keg-only and must be linked with --force
Note that doing so can interfere with building software.

~/Downloads/sc-im-dev-1/src (master *) $ brew link ncurses --force
Linking /usr/local/Cellar/ncurses/6.0_1... 930 symlinks created
```

**Comment by timfi** [comment]
This is because of the SIP (system integrity protection). You can't write to your /usr folder unless you turn this off. Currently this requires rebooting into recovery mode and running the command "csrutil disable" (and you can similarly reenable it with "csrutil enable"). Maybe changing the install location works, I'll try later.

**Comment by timfi** [comment]
If you change prefix=/usr to prefix=/usr/local, the compiler completes.

**Comment by andmarti1424** [comment]
This is an OS issue. Please try @timfi suggestion.

**Comment by incandescentman** [comment]
Thanks, `prefix=/usr/local` worked!
