### ISSUE TITLE
copy to system clipboard

### ISSUE THREAD

**Issue by schmeisers** [andmarti1424/sc-im#99]
Is there any way to copy cells to the system clipboard?

**Comment by andmarti1424** [comment]
Not really. Which system clipboard are you refering to? What is yous OS?

**Comment by schmeisers** [comment]
I'm on MacOS.   I was thinking something along the lines of the '+' buffer in vim.

**Comment by andmarti1424** [comment]
We might want to try to copy content to x clipboard, or better ... ¿ to wayland clipboard..?

**Comment by andmarti1424** [comment]
If you copy sc-im content to clipboard.. where would you paste it? A text editor??

**Comment by andmarti1424** [comment]
Anyone else interested in this feature?? Please leave a comment and vote for it.

**Comment by schmeisers** [comment]
> If you copy sc-im content to clipboard.. where would you paste it? A text editor??

Yes, most often a text editor (as part of composing an email) but also textfields on webpages, etc.

**Comment by svenn71** [comment]
I would love to be able to paste as asciidoc or markdown table in a different vim session.
Could probably be achieved by sending a selected range through a lua script? I have no knowledge on lua. I will have to read up on that scripting language

**Comment by andmarti1424** [comment]
Yes. You just need to know how to copy content to vim buffers

**Comment by roman65536** [comment]
Sven,not sure what you mean by copy paste to clipboard. On X there are different clipboards and is handled different from gnome, old X etc. Since sc is curses, curses may or may not have knowledge of X underneath and is usually limit to mouse location. 
Copy paste is the done by the terminal emulator, aka xterm or gnome-terminal etc. 

So far there is no such thing that Lua could handle range. That is partially due to sc design and how lua is embedded in to sc.basically lua is called similar as external function, with limited passing arguments possibilities. It was meant to extend sc with lua functions but not to take over control of sc.

**Comment by andmarti1424** [comment]
CLIPBOARD is handled differently in X, from OSX, or from Windows..
May be the best way to copy content to clipboard would be sending content directly to xclip in X or to pbcopy in OSX..

**Comment by andmarti1424** [comment]
Please update to latest commit in freeze branch. Now you can use the :ccopy to copy content to different clipboards.

**Comment by andmarti1424** [comment]
You can also try pasting content from other clipboards to Sc-im using the :cpaste command. This will give you the possibility to copy content from gnumeric or libreoffice calc to sc-im..

**Comment by andmarti1424** [comment]
Hello @schmeisers, @svenn71. Could you test this?

**Comment by schmeisers** [comment]
`:ccopy` is working great for me on Mac OS so far.  I'll keep testing and chime in with any problems.  Thank you very much for adding this!

**Comment by andmarti1424** [comment]
Did you test cpaste as well? for the ccopy test you did, did you set "copy_to_clipboard_delimitad_tab" variable to true? what were your DEFAULT_COPY_TO_CLIPBOARD_CMD in Makefile value?
Thanks.

**Comment by protist** [comment]
I just tested in Linux, and it mostly works. However `:ccopy` appears to copy what is *displayed* rather than what the cell *contains*. For example, if a cell is too narrow to show the whole content, sc-im displays `********` instead. When you `:ccopy`, these `*` are literally copied.

`:cpaste` seems to work generally, but it removes all spaces (I'm copying from gnumeric).

**Comment by andmarti1424** [comment]
That behaviour on ccopy was intended when you copy for pasting in a text editor in a  WYSIWYG form. Although Can be changed for pasting cobtent i  another spreadsheet ( it if you set the tab separator configuration variable). About the cpaste issue, what are those blank spaces getting removed? I believe i might be trimming those cell contents before copying to clipboard..

**Comment by andmarti1424** [comment]
Now entire content of fields are copied to clipboard if COPY_TO_CLIPBOARD_DELIMITED_TAB is set.
Otherwise WYSIWYG..

**Comment by protist** [comment]
Erm, I'm not sure if something else has changed, but when I try to `:ccopy` (with or without `COPY_TO_CLIPBOARD_DELIMITED_TAB` set), I'm now getting no change to the clipboard, and the following in the statusbar of sc-im.
```
A0 (10 2 0) <"foo" ning on /tmp/tmux-1000/default
```
I'm not even running `tmux`.

`:cpaste` is also broken now as well, but previously, if I tried to paste the following,
```
foo
bar baz
```
all spaces would be removed, i.e.
```
foo
barbaz
```

**Comment by andmarti1424** [comment]
Please type:
./scim --version
and check the values of DEFAULT_COPY_TO_CLIPBOARD_CMD and DEFAULT_PASTE_FROM_CLIPBOARD_CMD..
may be you build scim with tmux commands in  there, instead of xclip or pbpaste..

**Comment by protist** [comment]
Ah yes, thank you, you are right. I was able to modify the Makefile, and build with xclip.

One problem with the Makefile is that xclip `:cpaste` currently pastes from primary selection instead of the clipboard. (`ccopy` works from the clipboard as expected.) The following will fix it.
```
-#CFLAGS += -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""xclip -o"\"
+#CFLAGS += -DDEFAULT_PASTE_FROM_CLIPBOARD_CMD=\""xclip -o -selection clipboard"\"
```

* I tested `:cpaste` again, and as above, it's still eating up spaces.
* I tested `:ccopy` with `set COPY_TO_CLIPBOARD_DELIMITED_TAB=1` in `~/.scimrc`, but it still copied WYSIWYG.

**Comment by andmarti1424** [comment]
Thanks for that fix.
I will check the eating spaces issue.
About the second one. Please check you are using version 0.6.2, and check you set up correctly the variable copy_to_clipboard_delimited_tab, using the :set command.

**Comment by protist** [comment]
Hmm… yes, it doesn't appear to be set. So, as above, I have the following in `~/.scimrc`.
```
set COPY_TO_CLIPBOARD_DELIMITED_TAB=1
```
I also tried lower case.
```
set copy_to_clipboard_delimited_tab=1
```
In both cases,  after `:set` in scim, I see the following
```
copy_to_clipboard_delimited_tab=0
```
I even tried manually setting it during runtime in scim with
```
:set copy_to_clipboard_delimited_tab=1
```
and was informed
```
Config value changed: set copy_to_clipboard_delimited_tab=1
```
However, `:set` still shows the old (0) value, and `:ccopy` still doesn't work as expected.

**Comment by andmarti1424** [comment]
Please update to latest commit and try again

**Comment by protist** [comment]
Works perfectly! Thank you. The variable is set as expected from `~/.scimrc` and during runtime, and the copy works as I expected. Thank you for the quick and effective fix!
